# kitne container h ya kitni services frontend , backend
services:

  backend:
    build:
      context: ./backend

    container_name: cineverse-backend
# - => ye list ya array hota hai jaise env ka aise hi ports ka array
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend

    container_name: cineverse-frontend

    depends_on:
      - backend

    # Docker pehle backend container start karega,
# fir frontend container start karega.

# Ye sirf container ka startup order decide karta hai.
# Ye backend application ready hone ka wait nahi karta.
# Agar backend ko MongoDB connect hone me time lag raha ho,
# to frontend fir bhi start ho sakta hai.

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

# left side frontend mere mac ka path or right side app -> container ka
# : -> connect krdo host folder ko - container folder k sth (hot reload provide krta)
    volumes:
      - ./frontend:/app
      - /app/node_modules
#bind mounting
# /app → Mac se aayega (tera latest source code)
# /app/node_modules → Container ke Linux wale node_modules use honge

# Dependency container ke andar install karo ya image rebuild karo.