# kitne container h ya kitni services frontend , backend
services:

  backend:
    build:
      context: ./backend

    container_name: cineverse-backend
# - => ye list ya array hota hai jaise env ka aise hi ports ka array
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend

    container_name: cineverse-frontend

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

# left side frontend mere mac ka path or right side app -> container ka
# : -> connect krdo host folder ko - container folder k sth (hot reload provide krta)
    volumes:
      - ./frontend:/app
      - /app/node_modules
# bind mount lgte hi Ab /app pura replace ho gaya. Container ab image wala /app nahi dekh raha.
# Mac ke frontend folder me node_modules hai? Ho bhi sakta hai, nahi bhi.
## scene kya rhega ki app wale nodemodules jo linux m  hai uss s chalega wo 
# Jab bhi koi change hoga local folder me -> container me dikhega
# Aur container apne container node_modules use karega -> fast loading


## ⚠️ Agar new dependency install karni ho to sirf Mac par npm install karne se container ko nahi milegi,
# kyuki container Docker volume wala node_modules use kar raha hai.

# Dependency container ke andar install karo ya image rebuild karo.